# Generated by Django 3.2.18 on 2024-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240102_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='generes',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(upload_to='api/static/banners'),
        ),
    ]
